import React from 'react'

function Content() {
  return (
    <div className=' w-full mt-[100px] pl-[80px] pr-[80px] flex flex-row justify-between'>
        <div>
            <p className='text-[#CA6D18] text-[30px] font-serif'>Hobby</p>
            <div className='mt-[10px]'>
                <p className='text-[#222222] text-[30px] font-serif'>Weight Lifting</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, Oct 2019 - Present</p>
            </div>
            <p className='w-[380px] text-[23px] font-thin mt-[12px] text-justify'>
            Weight training is a common type of strength training for developing the strength, size of skeletal muscles and maintenance of strength. It uses the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose the force generated by muscle through concentric or eccentric contraction.
            </p>
            <div className='mt-[30px]'>
                <p className='text-[#222222] text-[30px] font-serif'>Cardio</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, Oct 2021 - Present</p>
            </div>
            <p className='w-[380px] text-[23px] font-thin mt-[12px] text-justify'>
            Aerobic exercise is physical exercise of low to high intensity that depends primarily on the aerobic energy-generating process. "Aerobic" is defined as "relating to, involving, or requiring oxygen", and refers to the use of oxygen to meet energy demands during exercise via aerobic metabolism adequately.
            </p>
        </div>
        <div className=' w-full ml-[150px]'>
            <p className='text-[#CA6D18] text-[30px] font-serif'>Education & Learning</p>
            <div className='mt-[30px]'>
                <p className='text-[#222222] text-[30px] font-serif'>Playground</p>
                <p className='text-[#797979] text-[25px] font-serif'>ST. Laurentius Manado</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, 2006 - 2007</p>
            </div>
            <div className='mt-[30px]'>
                <p className='text-[#222222] text-[30px] font-serif'>Primary School</p>
                <p className='text-[#797979] text-[25px] font-serif'>Eben Haezar Manado</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, 2007 - 2013</p>
            </div>
            <div className='mt-[30px]'>
                <p className='text-[#222222] text-[30px] font-serif'>Junior High School</p>
                <p className='text-[#797979] text-[25px] font-serif'>Eben Haezar Manado</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, 2013 - 2016</p>
            </div>
            <div className='mt-[30px]'>
                <p className='text-[#222222] text-[30px] font-serif'>Senior High School</p>
                <p className='text-[#797979] text-[25px] font-serif'>Eben Haezar Manado</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, 2016 - 2019</p>
            </div>
            <div className='mt-[30px]'>
                <p className='text-[#222222] text-[30px] font-serif'>College</p>
                <p className='text-[#797979] text-[25px] font-serif'>Klabat University</p>
                <p className='text-[#797979] text-[25px] font-serif'>Manado, 2019 - Present</p>
            </div>
        </div>
    </div>
  )
}

export default Content